_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./model_final_2d9806.pkl"
  
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (5000, 10000)
  MAX_ITER: 14000
OUTPUT_DIR: "output/R_101_FPN_3x"
